version: 1.2.{build}
branches:
  only:
  - main
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.png'
    - '**/*.jpg'
    - '**/*.svg'
    - '**/*.json'
    - '**/*.config'
    - '**/*.csproj'
    - '**/*.csproj.user'
    - 'Tests/'
image: Visual Studio 2022
configuration: Release
clone_depth: 5
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test: off
before_package:
- ps: .\build.ps1
artifacts:
- path: .\.nupkgs\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 5nV6F+Tvas3ELsrDTtYKAHd2AsgLfU+pELS3DS8NSYCCZmEfatnWeAV3CBO4pfIV
  skip_symbols: false
  on:
    branch: main
notifications:
- provider: Email
  to:
  - m.hyl@foxmail.com
  subject: inkslab.linq
  on_build_success: true
  on_build_failure: true